config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'pins#index'
  get 'home/about'
  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
    belongs_to :user
    has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
    searchkick
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?
  
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :email])
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)
      if @pin.save
        redirect_to @pin, notice: 'Pin was successfully created.'
      else
        render action: 'new'        
      end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end  
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    redirect_to pins_url, notice: 'Pin was successfully deleted'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image, :nickname, :price)
    end
end
def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized this pin" if @pin.nil?
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    
    <div class="navbar-header">
      <%= link_to 'Gallery', root_path, class: 'navbar-brand'%>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <form class="navbar-form navbar-right">
        <div class="form-group">
          <input id="searchitems" type="text" class="form-control" >
        </div>
        <button type="submit" class="btn btn-default">Search</button>
      </form>
      <!-- Tao tao cai list navigation bar chinh -->
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to "Add Item", new_pin_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
        <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
        <li><%= link_to "Join", new_user_registration_path %></li>
        <% end %>
        <li><%= link_to 'About', home_about_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/home/_jumbo.html.erb
<div class="jumbotron jumbotron-fluid">
  <h1>Welcome to my Cupcake</h1>
  <p>Pretty Cool, Uh huh!</p>
  <div class="container1">
  <% if user_signed_in? %>
  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-primary' %>
  <%= link_to "Edit", edit_user_registration_path, class: 'btn btn-default' %>
  <% else %>
  <%= link_to "Login", new_user_session_path, class:'btn btn-default'%>
  <%= link_to "Sign Up", new_user_registration_path , class:'btn btn-primary'%>
  <% end %>
  </div>
</div>

app/views/home/about.html.erb
<h1>About Us!</h1>
<p>My name is Hieu Nguyen and I'm building website for market</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title class="glyphicon glyphicon-film">Cupcake Chupy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'  %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'home/header' %>
<div class="container">
  <% flash.each do |name, msg| %>
  <%= content_tag(:div, msg, class: "alert alert-info")  %>
  <% end %>
<%= yield %>
</div>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'  %>  
</body>
</html>

app/views/pins/_form.html.erb
<%= form_for @pin, html: {multipart: true} do |f| %>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="panel panel-default">
    <div class="panel panel-heading"><h1>Editing Pin</h1></div>
        <div class="panel panel-body">
        <%= render 'form' %>
        </div>
    <div class="panel panel-footer">
        <%= link_to 'Show', @pin %> |
        <%= link_to 'Back', pins_path %>
    </div>
</div>

app/views/pins/index.html.erb
<%= render 'home/jumbo' unless user_signed_in? %>
<div class="transitions-enabled" id="pins" align="center">       
    <% @pins.each do |pin| %>
    <div class="box panel panel-default"> 
        <%= link_to image_tag(pin.image.url(:medium)), pin %></br>
        <%= pin.description %></br>
        <em><%= pin.user.nickname if pin.user %></em></br>
        <% if pin.user == current_user %>
        
        <%= link_to 'Edit', edit_pin_path(pin) %>
        <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
        
        <% end %>
        </br>
     </div>
    <% end %>
</div>    
<div class="center">
<%= will_paginate @pins , renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<div class="panel panel-default">
    <div class="panel panel-heading"><h1>New Pin</h1></div>
        <div class="panel panel-body">
            <%= render 'form' %>
        </div>
    <div class="panel panel-footer">
        <%= link_to 'Back', pins_path %>
    </div>
</div>

app/views/pins/show.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    
    <div class="panel panel-default">
      <div class="panel-heading center"><%= image_tag @pin.image.url(:medium) %></div>
        <div class="panel-body">
        <strong>Description:<strong> <%= @pin.description %></br>
        Updated At: <%= @pin.updated_at.to_s(:long) %></br>
        Price: <%= @pin.price %>
        </br>
        <em>Author:</em> <%= @pin.user.nickname if @pin.user %>
        </div>
        <% if @pin.user == current_user %>
        <div class="panel-footer">
          <%= link_to 'Edit', edit_pin_path(@pin) %> |
          <%= link_to 'Back', pins_path %>
        <% end %>
        </div>
</div>
</div>
</div>